.TH UPS-MONITOR 1 "09 February 2005" 
.SH NAME
RECORDING-MONITOR \- A program that helps you adjust audio recording levels
.SH SYNOPSIS
.B ups-monitor

.SH DESCRIPTION
.PP
Recording monitor lets you record analog audio and play it back simultaneously from your computer's sound card(s), while monitoring the loudness (input) level of the recording.
.PP
In the same spirit, you can choose which sound card you want to record from, which sound card you want to play back audio into, choose a recording input line and a recording input level mixer, adjust the input level (optionally having the program auto-lower the level if the input is too strong).

.SH OPTIONS
.TP
recording-monitor does not yet support any command-line options.

.SH BUGS
None are known

.SH AUTHOR
This very basic manual page was initially written by Arnaud Quette <arnaud.quette@mgeups.com>, for the Debian project fork of UPS monitor, and was modified by Manuel Amador <rudd-o@amautacorp.com>. It may be used by others.

